export const START_FORKS_SEARCH = "START_FORKS_SEARCH";
export const END_FORKS_SEARCH = "END_FORKS_SEARCH";
export const SUCCESSFUL_FORM_SUBMIT = "SUCCESSFUL_FORM_SUBMIT";
export const LIST_LAST_ITEM = "LIST_LAST_ITEM";
